# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Od programisty do bezpiecznika"
subtitle: "Version 0.2"
name: "Sidewinder22"
email: sidewinder22@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Od programisty do bezpiecznika - blog techniczny przedstawiający proces 
  nauki cyberbezpieczeństwa z pozycji programisty.  
baseurl: "" #http://localhost:4000/" #/od_programisty_do_bezpiecznika" # the subpath of your site, e.g. /blog
url: "https://sidewinder22.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "Sidewinder22/sidewinder22.github.io"
twitter_username: Sidewinder223
github_username:  Sidewinder22

# Build settings
#theme: minima 
#theme: jekyll-theme-midnight
remote_theme: mmistakes/minimal-mistakes
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


teaser: /assets/images/keyboard_mouse.jpg
logo: /assets/images/keyboard.jpg
locale: pl-PL


plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages

# urls:
# - text: About
# url: /about/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github: [metadata]

# To see feature posts
future: true

# Pagination
paginate: 5 # amount of posts to show
paginate_path: /page:num/


# Default settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_date: true
      author_profile: true


# Categories
category_archive:
  type: liquid
  path: /categories/

# Tags
tag_archive:
  type: liquid
  path: /tags/

# Turn on search
search : true

# Timezone
timezone: Europe/Warsaw 


# Author info
author:
  name     : "Sidewinder22"
  avatar   : "/assets/images/keyboard_mouse.jpg"
  bio      : "Programista C++, który chce się rozwijać w branży Cyberbezpieczeństwa."
  location : "Łódź, Poland"

twitter:
  username: "Sidewinder223"

# atom_feed:
#   hide: true
